### ISSUE TITLE
A1 - Memes

### ISSUE THREAD

**Issue by steven-hh-ding** [CISC-873/Information-2022#1]
It has to be appropriate : )

**Comment by AsmaaQ25** [comment]
![msg1121190165-6029](https://user-images.githubusercontent.com/25507214/153251316-b2f75086-ae2f-408e-88c1-2d9fd6244d37.jpg)

**Comment by Mahmoud-Khorshed-DS-AI** [comment]
![image](https://user-images.githubusercontent.com/99367639/153305921-221bfe63-dd1b-4c51-95b3-c6de246c2cfd.png)

**Comment by Eng-ZeyadTarek** [comment]
![download](https://user-images.githubusercontent.com/61242145/153406575-ee5f997d-5b2a-4fd6-a5a0-9f52a57b4b9b.jpg)

**Comment by Eng-ZeyadTarek** [comment]
![2zpi381vflkwz005yvua](https://user-images.githubusercontent.com/61242145/153406674-9acbdb8c-cfe7-4f6a-a450-4483a24c2cdf.jpg)

**Comment by fatmaaneis96** [comment]
![0cc96ad2-f133-41eb-9035-1b13bd3c0464](https://user-images.githubusercontent.com/99487858/153605272-3ef5afcb-d178-4e36-962d-26744af8e408.jpg)

**Comment by fatmaasy96** [comment]
![99ec078f-80a9-4633-8d79-e3d0fc02f000](https://user-images.githubusercontent.com/99487858/153605356-e8e5a51b-af1f-49c5-91ec-a85aa9b28916.jpg)

**Comment by nourhanmagdy1** [comment]
![Programming Meme😂](https://user-images.githubusercontent.com/81058010/153647857-d0ccd754-f6f4-4a2e-9c36-b05965d6a91d.jpg)

**Comment by abdelrahman-elhamoly** [comment]
![Statistician_memes_02](https://user-images.githubusercontent.com/27010333/153661826-338d6caa-82f8-400b-b761-27f1d8b94f72.jpg)

**Comment by MohamedIBnOmar** [comment]
![FB_IMG_1644614969984](https://user-images.githubusercontent.com/99500162/153673258-5965fc39-6653-4b9c-86a2-e30a07f0f017.jpg)

**Comment by Amany306** [comment]
![10fe79cc-2b69-487c-bcdf-06115bdb13ef](https://user-images.githubusercontent.com/70633054/153717671-a5b3fb03-0cc4-4236-970e-4c6aafc8e659.jpg)

**Comment by MohamedIBnOmar** [comment]
![FB_IMG_1644614956489](https://user-images.githubusercontent.com/99500162/153718680-6a10c2a6-8584-4821-b6c4-a6b2178a2beb.jpg)

**Comment by mahmoudbasha3** [comment]
![WhatsApp Image 2022-02-13 at 10 43 39 AM](https://user-images.githubusercontent.com/47246991/153745750-5ba14d38-9979-41d8-baba-0bd87a0f8987.jpeg)

**Comment by hendMohammed23** [comment]
![dd](https://user-images.githubusercontent.com/99394513/153867156-2fb83e36-1207-43ca-88a2-9c4372588d44.jpg)

**Comment by MoRamadan253** [comment]
![WhatsApp Image 2022-02-15 at 2 05 51 AM](https://user-images.githubusercontent.com/54215100/154264233-6db92eb0-e937-4eed-9192-bd1295c655f3.jpeg)

**Comment by SaraAL99** [comment]
![capture3](https://user-images.githubusercontent.com/99776202/154267532-44364dc5-ec31-4dcc-9164-1d3d587f66d8.jpeg)

**Comment by SaraAL99** [comment]
![capture1](https://user-images.githubusercontent.com/99776202/154267713-400dd236-e9a4-4951-b682-772d7b290075.jpeg)

**Comment by SaraAL99** [comment]
![Capture](https://user-images.githubusercontent.com/99776202/154267759-b8b227de-d483-4a2c-9a41-f63897481820.PNG)

**Comment by Mahmoud-SalehEldin** [comment]
![2l4p81b1pxp41](https://user-images.githubusercontent.com/45448948/154391321-86e4c583-5b3d-4ac4-80db-ee21fc603d34.jpg)

**Comment by Farah-178** [comment]
![image](https://user-images.githubusercontent.com/61745516/154472906-68f0559c-1808-446e-b9fd-2fb55879a94f.png)

**Comment by Israa-Elsayed** [comment]
![Meme1](https://user-images.githubusercontent.com/99852166/154699856-18cbabdb-df65-4c3d-ae16-fd1fbbf40f9a.png)

**Comment by Israa-Elsayed** [comment]
![Meme2](https://user-images.githubusercontent.com/99852166/154702939-cb360969-6f0f-441a-9021-4683b97abfaf.png)

**Comment by Israa-Elsayed** [comment]
![Meme-4](https://user-images.githubusercontent.com/99852166/154713830-8c8765a9-8564-4269-9ccb-fafe8ef7a55f.png)

**Comment by AsmaaQ25** [comment]
![image](https://user-images.githubusercontent.com/25507214/154958671-bb28da3a-0027-4d97-969e-fac902eb516f.png)

**Comment by mohamedmakram** [comment]
![1_8jAT7ocXcZTw5TcyiUiNIA](https://user-images.githubusercontent.com/39784239/155028524-b0592bfc-162d-4a8a-a445-7330b9984f22.jpeg)
![1_3PQTLetI6v7TDFw7REu3dg](https://user-images.githubusercontent.com/39784239/155028527-c85f31a3-7b0a-4f2a-a7ee-2eb52f499c3e.jpeg)

**Comment by Ahmedanwernouser** [comment]
![meme 5](https://user-images.githubusercontent.com/87036725/155046682-577a55b9-5146-4c27-af78-ba1da21c31be.jpg)

**Comment by Ahmedanwernouser** [comment]
![meme 4](https://user-images.githubusercontent.com/87036725/155046722-a17c1519-7fd7-491f-a56c-b82c59ea4d30.jpg)
![meme 3](https://user-images.githubusercontent.com/87036725/155046725-e25de51e-0d26-44e4-b5c4-8ee25d9170bd.jpg)
![meme2](https://user-images.githubusercontent.com/87036725/155046727-ad2e6d14-a9b1-4890-8c63-7a8e8f5cff08.jpg)
![meme 1](https://user-images.githubusercontent.com/87036725/155046729-0a79a358-6da5-4798-a549-c43eb53ab540.jpg)

**Comment by AsmaaQ25** [comment]
Give me the bill Morpheus, NOWWWWW

**Comment by Israa-Elsayed** [comment]
> ![Meme1](https://user-images.githubusercontent.com/99852166/154699856-18cbabdb-df65-4c3d-ae16-fd1fbbf40f9a.png)
![Meme 5](https://user-images.githubusercontent.com/99852166/155205843-d5b86128-36b6-4f61-82bb-d3732ac7c09a.png)

**Comment by ahmedsallem** [comment]
![cat](https://user-images.githubusercontent.com/100295040/157364581-577c72d2-213f-4b96-a904-121401fe1600.jpg)

**Comment by O-A-M** [comment]
Hyperparameter Tuning...

https://user-images.githubusercontent.com/43207758/157567300-d24f5699-c1d1-49f2-8886-a12d11b4233d.mp4

**Comment by abdelrahman-elhamoly** [comment]
![21392935](https://user-images.githubusercontent.com/27010333/157631597-918bee39-12f2-4aad-b3aa-47108609ef74.jpg)

**Comment by EsraaMohamed0301** [comment]
![meme3](https://user-images.githubusercontent.com/101602589/158266619-620dc618-640a-4704-a9db-bfd117e1421a.jpeg)

**Comment by MohamedIBnOmar** [comment]
![Uploading FB_IMG_1647865309611.jpg…]()

**Comment by Aya-Allah-Ali** [comment]
![image](https://user-images.githubusercontent.com/102191992/159588868-1c5a4cd1-acf5-4ff5-8fd1-58e9f4f8c0b7.png)

**Comment by Aya-Allah-Ali** [comment]
![image](https://user-images.githubusercontent.com/102191992/159588978-d9f87fa0-928a-47cb-a793-4bc51f174aab.png)


Image address
https://journeys.dartmouth.edu/folklorearchive/files/2020/06/memeAI2.jpg
link address
https://www.google.com/url?sa=i&url=https%3A%2F%2Fjourneys.dartmouth.edu%2Ffolklorearchive%2Fauthor%2Ff0034jj%2F&psig=AOvVaw1_Cesa_PvUoecctFTXYi8u&ust=1648074071675000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCIjI1MDg2vYCFQAAAAAdAAAAABBA

**Comment by Aya-Allah-Ali** [comment]
![image](https://user-images.githubusercontent.com/102191992/159589207-35e62b43-2040-4ff8-b1f1-296e62377d0e.png)

Image address :
https://memegenerator.net/img/instances/50431999.jpg

link address :
https://www.google.com/url?sa=i&url=https%3A%2F%2Fmemegenerator.net%2Finstance%2F50431999%2Fdog-scientist-datamining-parameter-tuning-i-have-idea-what-im-doing&psig=AOvVaw0hxN6whbltOY8ranREgH8K&ust=1648073707832000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCPiF7JDf2vYCFQAAAAAdAAAAABAD

**Comment by Aya-Allah-Ali** [comment]
![image](https://user-images.githubusercontent.com/102191992/159657371-4a5fc00f-e34a-4b1f-bab1-cf54a8341a55.png)


link address :
https://www.google.com/url?sa=i&url=https%3A%2F%2Fjourneys.dartmouth.edu%2Ffolklorearchive%2Fcategory%2F20s-ai-memes%2F&psig=AOvVaw2sFQYirStoMgKj25aki9Ba&ust=1648073259596000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCKDjnLzd2vYCFQAAAAAdAAAAABA1

image address :
https://journeys.dartmouth.edu/folklorearchive/files/2020/06/AI-meme.jpg

**Comment by esraamahmoud77** [comment]
![169150755_10157561146231601_5577348515036767978_n](https://user-images.githubusercontent.com/47893416/226123941-80d17d10-9963-4745-b853-e7db072c3e96.jpg)

**Comment by esraamahmoud77** [comment]
![240720430_4414051005343107_385816203923881418_n](https://user-images.githubusercontent.com/47893416/226123971-79255a1c-8d59-4773-a882-7199253c4f1a.jpg)

**Comment by esraamahmoud77** [comment]
![245338366_10225139087094582_7525775838373648493_n](https://user-images.githubusercontent.com/47893416/226124107-c5746084-d6d0-49c8-a564-d6171ac0b09c.jpg)

**Comment by esraamahmoud77** [comment]
![271973116_4895747750506761_7454146879629076838_n](https://user-images.githubusercontent.com/47893416/226456269-e9c89621-f5b3-4ed3-81be-96fc8d1e0010.jpg)

**Comment by 012mariam** [comment]
![1_lBRfBvVMaqvnLApxcclQAA](https://user-images.githubusercontent.com/48841649/226671079-fcf03873-e435-4c25-95ba-f61164aba255.jpg)

**Comment by 012mariam** [comment]
![1_wTSMOpXLHyxbsv1OUMt_KQ](https://user-images.githubusercontent.com/48841649/226671473-c3c04d31-f9de-4723-ae0c-e96d730b935b.jpg)

**Comment by hananfared** [comment]
![Trump_Big_Data_Meme](https://user-images.githubusercontent.com/101905795/226779103-427e83bb-c65c-4e77-8fa3-d0142f9b6036.jpg)

**Comment by hananfared** [comment]
![AI Memes _ best data science memes _ data analytics memes _ best data science Jokes _ data memes 2](https://user-images.githubusercontent.com/101905795/226780107-8e8e17ee-3d4a-4255-a35a-5536b6f21595.jpg)

**Comment by hananfared** [comment]
![05xlvswuhfg41](https://user-images.githubusercontent.com/101905795/226940609-71b69677-b7a1-46c7-9b30-2d3a3e44cdfb.jpg)

**Comment by hananfared** [comment]
![regularization-meme-67d8abb4bf42d7b10781decba976208c-5ceff](https://user-images.githubusercontent.com/101905795/226940920-b149bf79-741c-4270-ae48-2d4a41f89f5f.jpeg)

**Comment by AliAbdelkaderAboelela** [comment]
![f8a31571-4a6a-46b1-8f99-d448276c08ac](https://user-images.githubusercontent.com/88301517/228230750-5e41d27f-f526-4f1a-a0f9-e605904ee0cf.jpg)

**Comment by esraamahmoud77** [comment]
![d44ec33f2c4434862c2b99f168dcf4a4](https://user-images.githubusercontent.com/47893416/229509645-71c869b5-63ef-4aad-af38-3476aef74c4f.jpg)

**Comment by esraamahmoud77** [comment]
![d1873d7dd728b75b2bb5f042b95d7d8e](https://user-images.githubusercontent.com/47893416/229512227-a02d2c4f-ed80-4f1c-b748-c452f451febe.jpg)

**Comment by Eslamelreedy** [comment]
![image](https://user-images.githubusercontent.com/60406816/230696840-a5ee4085-09d2-4020-a569-b77b75bcfae7.png)

**Comment by Eslamelreedy** [comment]
![image](https://user-images.githubusercontent.com/60406816/230696887-9592c2b4-29ea-4e8d-91a6-b0ad2199c116.png)

**Comment by HossamAbdelrhman** [comment]
![ML_mem](https://github.com/CISC-873/Information-2022/assets/37634832/7102d867-cc69-48ce-8ed4-19c5331156fa)

**Comment by HGamalElDin** [comment]
![image](https://github.com/CISC-873/Information-2022/assets/77637172/466a1b96-d074-45ff-838d-e2309bde105b)

**Comment by HGamalElDin** [comment]
![deep-learning-_mlmuff fit_lim size_1050x](https://github.com/CISC-873/Information-2022/assets/77637172/54e66358-887e-4cfb-ad7a-7487710e2fab)

**Comment by iamshahd** [comment]
![image](https://github.com/CISC-873/Information-2022/assets/55947168/33470998-253c-4c62-90cc-4c13304a7b44)
