### ISSUE TITLE
Meme competition 2022-fall

### ISSUE THREAD

**Issue by steven-hh-ding** [CISC-873/Information-2022#2]
submit your ...  favourite meme

**Comment by elzadgeorge** [comment]
![images](https://user-images.githubusercontent.com/109773927/192767651-da8b299a-b79e-4815-9509-1fc76c6e73fc.jpeg)

**Comment by emedema** [comment]
<img width="488" alt="bfu_data_meme" src="https://user-images.githubusercontent.com/26208098/192907415-2bf9d18b-ef68-46db-9600-a999c2916d86.png">

**Comment by miladsoltany** [comment]
![gan_training](https://user-images.githubusercontent.com/44018277/193065231-40315c9f-4498-454e-86a0-67866bb44f4b.png)

**Comment by yiping-jia** [comment]
![IMG_2074](https://user-images.githubusercontent.com/80622866/193175090-d5afd0c2-a87a-4087-987f-7e22d08aa1e2.JPG)

**Comment by 16sl75** [comment]
![Meme](https://user-images.githubusercontent.com/57738276/193178682-6f3698d7-e712-4561-8390-59852c464fd3.jpeg)

**Comment by therealronnyrochwerg** [comment]
[meme1.pdf](https://github.com/CISC-873/Information-2022/files/9680444/meme1.pdf)
[meme2.pdf](https://github.com/CISC-873/Information-2022/files/9680445/meme2.pdf)

**Comment by therealronnyrochwerg** [comment]
![meme1.pdf](https://github.com/CISC-873/Information-2022/files/9680627/meme1.pdf)
![meme2.pdf](https://github.com/CISC-873/Information-2022/files/9680628/meme2.pdf)

**Comment by katin139** [comment]
<img width="488" alt="Screen Shot 2022-09-30 at 12 03 03 AM" src="https://user-images.githubusercontent.com/60240062/193187890-d75ce6cd-d9a5-4424-bc88-e992aa0ed416.png">

**Comment by ronrochwerg** [comment]
![meme1-1](https://user-images.githubusercontent.com/26328127/193188147-f8601c33-e8db-4435-907f-bc5b160da0c5.png)
![meme2-1](https://user-images.githubusercontent.com/26328127/193188149-a4841024-7510-440a-b09f-355454f4bf72.png)

**Comment by katin139** [comment]
<img width="486" alt="Screen Shot 2022-09-29 at 11 39 52 PM" src="https://user-images.githubusercontent.com/60240062/193188221-3ea8c813-6c6f-4d69-87a7-da4db25b2013.png">

**Comment by JacksonCaii** [comment]
![meme](https://user-images.githubusercontent.com/94489215/193332261-1122dd9e-a33e-4239-95ba-9ff6ad79d9f0.jpeg)

**Comment by Wenhuan512** [comment]
![IMG_3673](https://user-images.githubusercontent.com/109938829/193365301-cbd18675-49ed-4562-b9e6-73d98c6f7a82.jpg)
![IMG_3674](https://user-images.githubusercontent.com/109938829/193365308-f7ee7bd1-ce0b-47a1-8ecc-d95ffe63498c.jpg)

**Comment by Wenhuan512** [comment]
![IMG_3673](https://user-images.githubusercontent.com/109938829/193365364-3f1c04fa-3c5d-4487-b66a-9b5cc5423cf5.jpg)

**Comment by Wenhuan512** [comment]
![IMG_3674](https://user-images.githubusercontent.com/109938829/193365378-cc932307-c34f-4cee-9876-d3fc1a64c3f3.jpg)

**Comment by Irene-ML** [comment]
![ae6c7c797f1584ad686fbd7c148ba78a](https://user-images.githubusercontent.com/112911856/193377813-7f33ac7b-ba49-4df4-8595-c7a767e61f44.jpeg)

**Comment by MahdiyarMM** [comment]
<img width="867" alt="Screen Shot 2022-10-01 at 10 43 11 PM" src="https://user-images.githubusercontent.com/45335894/193435549-47803d75-cded-45c1-81e8-bfea4eb196c1.png">

**Comment by Ian-Goodall-Halliwell** [comment]
https://user-images.githubusercontent.com/90027009/193492469-5f9ac3c4-e174-4cb9-88d5-349e72ef5ef7.mp4

**Comment by aaron6yi** [comment]
![oneyear](https://user-images.githubusercontent.com/56087909/193601687-6acd9d73-d1c8-4816-8995-24bf4e3ff567.jpg)

**Comment by SuruthyS** [comment]
> submit your ... favourite meme

![image](https://user-images.githubusercontent.com/109919083/193651364-02ac568e-4991-41d5-bef2-e2af8bdfaa18.png)

**Comment by Vidhi2014** [comment]
[](url)
![meme](https://user-images.githubusercontent.com/26875769/193718431-41eed6b7-53fa-4c7e-aad3-3356012a8f55.jpeg)

**Comment by ejyach** [comment]
![stool](https://user-images.githubusercontent.com/60582260/193918145-3391209f-b100-427c-8a70-125496ef1add.png)

**Comment by steven-hh-ding** [comment]
> ![stool](https://user-images.githubusercontent.com/60582260/193918145-3391209f-b100-427c-8a70-125496ef1add.png)

this one has to win : )

**Comment by JacksonCaii** [comment]
![meme2](https://user-images.githubusercontent.com/94489215/197451749-d3612b48-4e34-4ded-b119-fef62aa47d59.jpeg)

**Comment by miladsoltany** [comment]
![176154093_1227152784405886_4030526489742358653_n](https://user-images.githubusercontent.com/44018277/197568350-be44e114-d989-45dd-892d-5b68a72b2393.jpg)

**Comment by 16sl75** [comment]
![meme](https://user-images.githubusercontent.com/57738276/197600014-337510fe-6b97-4160-81c9-6c3dc62ce288.jpeg)

**Comment by SuruthyS** [comment]
![image](https://user-images.githubusercontent.com/109919083/198165927-dc15ffb0-b9ed-4e9c-9604-0c61e68c436e.png)

**Comment by emedema** [comment]
<img width="486" alt="dm873meme2" src="https://user-images.githubusercontent.com/26208098/198402018-96af1fc3-ce35-487b-8af4-f47d28247763.png">

**Comment by MahdiyarMM** [comment]
![tumblr_31c3a5fd3f5bfc8d33007ab52da9c5e0_5492729e_1280](https://user-images.githubusercontent.com/45335894/198902386-f8cd532d-a6c8-4aeb-8b98-2c1425a457e5.jpeg)

**Comment by Wenhuan512** [comment]
![IMG_4168](https://user-images.githubusercontent.com/109938829/199088958-651f64e6-f078-4ae3-9fd9-32a9697f178c.jpg)

**Comment by yiping-jia** [comment]
![image](https://user-images.githubusercontent.com/80622866/199149707-da31d23c-b27c-4547-9a09-640c3e9d1e64.png)
![image](https://user-images.githubusercontent.com/80622866/199149875-b6f6a85e-ac1f-4d0d-ac7a-77758574ec56.png)

**Comment by 16sl75** [comment]
![meme](https://user-images.githubusercontent.com/57738276/199152004-5ebf1b42-6c69-4971-9e00-6b7a6fb86341.jpg)

**Comment by aaron6yi** [comment]
![WeChat Screenshot_20221031234810](https://user-images.githubusercontent.com/56087909/199154512-cd008560-9dc7-4473-89f3-f50722ea8059.png)

**Comment by Wenhuan512** [comment]
![IMG_4222](https://user-images.githubusercontent.com/109938829/202627590-aa2c6a42-dc1e-4975-b49a-01cc00ab6434.jpg)

**Comment by Wenhuan512** [comment]
![model_train](https://user-images.githubusercontent.com/109938829/202630258-080007d9-d5d7-4c49-b345-c8c896f7d8ab.jpg)

**Comment by Wenhuan512** [comment]
![new_associationrules](https://user-images.githubusercontent.com/109938829/202630268-b5ec4c3b-2a59-4550-a4fc-930c11bbf7f0.jpg)

**Comment by steven-hh-ding** [comment]
Thanks everyone for the contribution! ❤️
